In [26]:
# open file 
mni = open("input.txt","r");

# reading file content line by line
polymer_template = readline(mni)
readline(mni)
pairs = Dict(); 

for line in readlines(mni)
    pairs[split(line," -> ")[1]] = split(line," -> ")[2]
end

In [27]:
function insert_polymer(cur_polymer, dict)
    new_polymer = []
    for (a, b) in zip(cur_polymer[1:end-1], cur_polymer[2:end])
        push!(new_polymer, string(a))
        push!(new_polymer, string(dict[a*b]))
    end
    
    push!(new_polymer, string(cur_polymer[end]))
    
    return new_polymer
end

insert_polymer (generic function with 1 method)

In [28]:
polymer_list = []
polymer_dict = copy(pairs)

push!(polymer_list, polymer_template)

for i in 1:10
    push!(polymer_list, insert_polymer(polymer_list[end], polymer_dict));
end

In [29]:
counts = Dict()
for elem in polymer_list[end]
    if elem in keys(counts)
        counts[elem] += 1
    else
        counts[elem] = 1
    end
end

counts
counts2 = copy(counts)

Dict{Any, Any} with 10 entries:
  "F" => 3962
  "B" => 1690
  "S" => 1782
  "C" => 551
  "P" => 3637
  "N" => 2193
  "V" => 1227
  "K" => 999
  "H" => 1645
  "O" => 1771

In [30]:
minv = 10000000
maxv = 0

for val in values(counts)
    minv = val < minv ? val : minv
    maxv = val > maxv ? val : maxv
end

@show (maxv, minv, maxv-minv)

(maxv, minv, maxv - minv) = (3962, 551, 3411)


(3962, 551, 3411)

In [31]:
# Part 2

In [57]:
function expand_and_count(pair, rule_dict, memo, cur_step, max_step, distinct_elem)
    pair_str = string(pair[1] * pair[2])
    
    if sum(memo[pair_str][cur_step, 1:end]) > 0
        #@show ("Found", pair_str, cur_step, memo[pair_str][cur_step, 1:end], sum(memo[pair_str][cur_step, 1:end]))
        return memo[pair_str][cur_step, 1:end]
    end
    
    if cur_step < max_step 
        left_pair = rule_dict[pair_str]
        left_count = expand_and_count(left_pair, rule_dict, memo, cur_step + 1, max_step, distinct_elem)
        right_pair = string(rule_dict[pair_str][end], string(pair[end]))
        right_count = expand_and_count(right_pair, rule_dict, memo, cur_step + 1, max_step, distinct_elem)
        
        memo[pair_str][cur_step, 1:end] = left_count + right_count
        
        mid = string(rule_dict[pair_str][2])
        idx_mid = indexin([mid], distinct_elem)[1]
        memo[pair_str][cur_step, idx_mid] -= 1
    else
        
        left = string(rule_dict[pair_str][1])
        mid = string(rule_dict[pair_str][2])
        right = string(pair[2])
        
        idx_left = indexin([left], distinct_elem)[1]
        idx_mid = indexin([mid], distinct_elem)[1]
        idx_right = indexin([right], distinct_elem)[1]
        
        #@show (pair_str, rule_dict[pair_str], cur_step, mid, idx_mid, distinct_elem, memo[pair_str][cur_step, idx_left])
        memo[pair_str][cur_step, idx_left] += 1
        memo[pair_str][cur_step, idx_mid] += 1
        memo[pair_str][cur_step, idx_right] += 1
    end
    
    #@show ("Add", pair_str, cur_step, memo[pair_str][cur_step, 1:end])
    
    return memo[pair_str][cur_step, 1:end]
end

expand_and_count (generic function with 1 method)

In [58]:
function initialize_memo(pairs, steps, distinct_elem)
    memo = Dict()
    for pair in keys(pairs)
        pair_counts = zeros(Int64, max, length(distinct_elem))
        pair_str = string(pair)
        memo[pair_str] = pair_counts
    end
    
    return memo
end    
    

initialize_memo (generic function with 1 method)

In [59]:
mni = open("input.txt","r");


# reading file content line by line
polymer_template = readline(mni)
readline(mni)

distinct_elem = []
for elem in values(pairs)
    if !(string(elem) in distinct_elem) 
        push!(distinct_elem, string(elem))
    end
end
sort!(distinct_elem)

pairs2 = Dict(); 
for line in readlines(mni)
    pairs2[split(line," -> ")[1]] = string(split(line," -> ")[1][1]) * split(line," -> ")[2]
end

In [61]:
max = 40 #steps
memo = initialize_memo(pairs2, max, distinct_elem)
tot_count = copy(memo[string(polymer_template[1], polymer_template[2])][1, 1:end])

for i =  2:length(polymer_template)
    @show pair = string(polymer_template[i-1], polymer_template[i])
    cur_count = expand_and_count(pair, pairs2, memo, 1, max, distinct_elem)
  
    tot_count += cur_count 
    #for ckey in keys(cur_count)
    #    if ckey in keys(tot_count)
    #        tot_count[ckey] += cur_count[ckey]
    #    else
    #        tot_count[ckey] = cur_count[ckey]
    #    end   
    #end 
end

for i =  2:length(polymer_template) - 1  
    @show cur = string(polymer_template[i])
    @show idx = indexin([cur], distinct_elem)[1]
    tot_count[idx] -= 1
end
    



pair = string(polymer_template[i - 1], polymer_template[i]) = "SN"
pair = string(polymer_template[i - 1], polymer_template[i]) = "NP"
pair = string(polymer_template[i - 1], polymer_template[i]) = "PV"
pair = string(polymer_template[i - 1], polymer_template[i]) = "VP"
pair = string(polymer_template[i - 1], polymer_template[i]) = "PF"
pair = string(polymer_template[i - 1], polymer_template[i]) = "FC"
pair = string(polymer_template[i - 1], polymer_template[i]) = "CP"
pair = string(polymer_template[i - 1], polymer_template[i]) = "PP"
pair = string(polymer_template[i - 1], polymer_template[i]) = "PK"
pair = string(polymer_template[i - 1], polymer_template[i]) = "KS"
pair = string(polymer_template[i - 1], polymer_template[i]) = "SB"
pair = string(polymer_template[i - 1], polymer_template[i]) = "BN"
pair = string(polymer_template[i - 1], polymer_template[i]) = "NS"
pair = string(polymer_template[i - 1], polymer_template[i]) = "SP"
pair = string(polymer_template[i - 1], polymer_template[i]) = 

In [62]:
@show polymer_template
@show distinct_elem
tot_count

@show findmax(tot_count)
@show findmin(tot_count)

polymer_template = "SNPVPFCPPKSBNSPSPSOF"
distinct_elem = Any["B", "C", "F", "H", "K", "N", "O", "P", "S", "V"]
findmax(tot_count) = (7780153820616, 3)
findmin(tot_count) = (302338065046, 2)


(302338065046, 2)

In [63]:
counts2

Dict{Any, Any} with 10 entries:
  "F" => 3962
  "B" => 1690
  "S" => 1782
  "C" => 551
  "P" => 3637
  "N" => 2193
  "V" => 1227
  "K" => 999
  "H" => 1645
  "O" => 1771

In [64]:
7780153820616 -  302338065046

7477815755570

In [47]:
memo["SV"][end-10:end, 1:end]

11×10 Matrix{Int64}:
 234  79  173  170  90  229  291  364  226  193
 125  42   76   75  39  109  155  181  116  107
  64  23   31   33  17   49   88   88   61   59
  34  11   13   14   6   22   46   42   34   35
  16   6    5    6   2    9   27   20   19   19
  10   3    2    2   0    3   14   10   10   11
   6   2    0    1   0    1    7    4    6    6
   4   1    0    0   0    0    3    1    4    4
   1   1    0    0   0    0    1    0    3    3
   1   0    0    0   0    0    1    0    2    1
   1   0    0    0   0    0    0    0    1    1

In [13]:
ckey = "H"
a = indexin([ckey], distinct_elem)
distinct_elem


4-element Vector{Any}:
 "B"
 "C"
 "H"
 "N"

In [14]:
memo

Dict{Any, Any} with 16 entries:
  "HB" => [0 0 0 0; 250 88 74 101; … ; 2 1 2 0; 1 1 1 0]
  "CH" => [0 0 0 0; 210 121 88 94; … ; 1 1 3 0; 1 1 1 0]
  "BC" => [0 0 0 0; 342 1 0 170; … ; 3 1 0 1; 2 1 0 0]
  "HC" => [0 0 0 0; 0 0 0 0; … ; 2 2 1 0; 1 1 1 0]
  "NN" => [606 89 0 330; 0 0 0 0; … ; 0 0 0 0; 0 0 0 0]
  "HH" => [0 0 0 0; 0 0 0 0; … ; 0 2 2 1; 0 0 2 1]
  "BH" => [0 0 0 0; 0 0 0 0; … ; 1 0 3 1; 1 0 2 0]
  "CC" => [0 0 0 0; 0 0 0 0; … ; 1 3 0 1; 0 2 0 1]
  "NB" => [0 0 0 0; 342 0 0 171; … ; 3 0 0 2; 2 0 0 1]
  "BB" => [0 0 0 0; 0 0 0 0; … ; 4 0 0 1; 2 0 0 1]
  "NH" => [0 0 0 0; 0 0 0 0; … ; 2 1 1 1; 0 1 1 1]
  "CN" => [0 0 0 0; 265 89 0 159; … ; 0 3 0 2; 0 2 0 1]
  "BN" => [0 0 0 0; 0 0 0 0; … ; 3 0 0 2; 2 0 0 1]
  "HN" => [0 0 0 0; 0 0 0 0; … ; 1 2 1 1; 0 1 1 1]
  "CB" => [460 209 161 195; 0 0 0 0; … ; 2 2 1 0; 1 1 1 0]
  "NC" => [683 1 0 341; 341 1 0 171; … ; 3 1 0 1; 1 1 0 1]

In [15]:
count_list = [] 
for polymer in polymer_list
    counts = Dict()
    for elem in polymer
        if string(elem) in keys(counts)
            counts[string(elem)] += 1
        else
            counts[string(elem)] = 1
        end
    end
    
    push!(count_list, counts)
end

In [16]:
count_list

11-element Vector{Any}:
 Dict{Any, Any}("B" => 1, "C" => 1, "N" => 2)
 Dict{Any, Any}("B" => 2, "C" => 2, "N" => 2, "H" => 1)
 Dict{Any, Any}("B" => 6, "C" => 4, "N" => 2, "H" => 1)
 Dict{Any, Any}("B" => 11, "C" => 5, "N" => 5, "H" => 4)
 Dict{Any, Any}("B" => 23, "C" => 10, "N" => 11, "H" => 5)
 Dict{Any, Any}("B" => 46, "C" => 15, "N" => 23, "H" => 13)
 Dict{Any, Any}("B" => 98, "C" => 31, "N" => 48, "H" => 16)
 Dict{Any, Any}("B" => 199, "C" => 48, "N" => 99, "H" => 39)
 Dict{Any, Any}("B" => 417, "C" => 96, "N" => 205, "H" => 51)
 Dict{Any, Any}("B" => 845, "C" => 152, "N" => 422, "H" => 118)
 Dict{Any, Any}("B" => 1749, "C" => 298, "N" => 865, "H" => 161)

In [17]:
#F       N
#F   S   N
#F K S B N
#FSKOSSBPN
#

id(s) = indexin([s], distinct_elem)[1]
pair = "FN"
step = 8


for (i, elem) in enumerate(distinct_elem)
    @show (elem, memo[pair][step, id(elem)])
end

LoadError: KeyError: key "FN" not found

In [18]:

pairs["BN"]

"B"

In [19]:
mni = open("input.txt","r");


# reading file content line by line
polymer_template = readline(mni)
readline(mni)

distinct_elem = []
for elem in values(pairs)
    if !(string(elem) in distinct_elem) 
        push!(distinct_elem, string(elem))
    end
end
sort!(distinct_elem)

pairs2 = Dict(); 
for line in readlines(mni)
    pairs2[split(line," -> ")[1]] = string(split(line," -> ")[1][1]) * split(line," -> ")[2]
end

max = 10 #steps
memo = initialize_memo(pairs2, max, distinct_elem)

expand_and_count("FN", pairs2, memo, 1, max, distinct_elem);

LoadError: KeyError: key "FN" not found

In [53]:
@show distinct_elem

memo["SV"][1, 1:end]

distinct_elem = Any["B", "C", "F", "H", "K", "N", "O", "P", "S", "V"]


20×10 Matrix{Int64}:
 87920  29201  181441  120076  64871  124352  94079  181686  105562  59389
 45297  15074   86418   59408  32136   62588  48589   90627   53186  30966
 23359   7793   41010   29253  15894   31508  25203   45243   26727  16155
 12077   4029   19340   14361   7797   15805  13081   22649   13464   8470
  6239   2100    9084    6999   3819    7932   6825   11338    6750   4451
  3243   1084    4218    3396   1848    3950   3575    5699    3407   2349
  1682    571    1952    1628    895    1970   1876    2854    1709   1248
   874    294     885     776    420     968   1001    1443     867    665
   452    154     401     362    199     477    532     722     436    362
   234     79     173     170     90     229    291     364     226    193
   125     42      76      75     39     109    155     181     116    107
    64     23      31      33     17      49     88      88      61     59
    34     11      13      14      6      22     46      42      34     35
    

In [54]:
polymer_list = []
polymer_dict = copy(pairs)

push!(polymer_list, "SV")

for i in 1:25
    push!(polymer_list, insert_polymer(polymer_list[end], polymer_dict));
end
counts = Dict()
for elem in polymer_list[end]
    if elem in keys(counts)
        counts[elem] += 1
    else
        counts[elem] = 1
    end
end

counts

Dict{Any, Any} with 10 entries:
  "F" => 7058172
  "B" => 2473376
  "S" => 3237688
  "C" => 814333
  "P" => 5981203
  "N" => 3787781
  "V" => 1600401
  "K" => 2084943
  "H" => 3905381
  "O" => 2611155

In [22]:
function expand_and_count(pair, rule_dict, memo, cur_step, max_step)
    
    memokey = string(string(pair[1]), string(pair[2]))
    
    if memokey in keys(memo)
        if(memo[memokey])
        return memo_arr[memokey]
    end
    
    count = Dict()
    
    if cur_step < max_step 
        
        left_pair = rule_dict[string(pair[1] * pair[2])]
        left_count = expand_and_count(left_pair, rule_dict, memo_arr, cur_step + 1, max_step)
        right_pair = string(rule_dict[string(pair[1] * pair[2])][end], string(pair[end]))
        right_count = expand_and_count(right_pair, rule_dict, memo_arr, cur_step + 1, max_step)
        
        for lkey in keys(left_count)
            count[lkey] = left_count[lkey]
        end
        
         for rkey in keys(right_count)
            if rkey in keys(count)
                count[rkey] += right_count[rkey]
            else
                count[rkey] = right_count[rkey]
            end   
        end
    else
        count[string(pair[1])] = 1
        
        if string(rule_dict[string(pair[1] * pair[2])][2]) in keys(count)
            count[string(rule_dict[string(pair[1] * pair[2])][2])] += 1
        else
            count[string(rule_dict[string(pair[1] * pair[2])][2])] = 1
        end
        
        if string(pair[2]) in keys(count)
            count[string(pair[2])] += 1
        else
            count[string(pair[2])] = 1
        end
    end
    
    @show [memokey, count]
    memo_arr[memokey] = count
                    
    return count
end

LoadError: syntax: incomplete: "function" at In[22]:1 requires end