In [1]:
# open file 
mni = open("input.txt","r");

# reading file content line by line

pairs = []; 
folds = [];
for line in readlines(mni)
    if length(split(line,",")) > 1
        push!(pairs,[parse(Int64, val) + 1 for val in split(line,",")])
    elseif line != ""
        dir = split(split(line,"=")[1]," ")[end]
        val = parse(Int64, split(line,"=")[2]) + 1
        push!(folds, (dir, val))
    end
end

In [2]:
function find_max(pairs)
    xmax = 0
    ymax = 0
    for row in pairs
        xmax = max(row[1], xmax)[1]
        ymax = max(row[2], ymax)[1]
    end
    
    return (xmax, ymax)
end

find_max (generic function with 1 method)

In [3]:
function make_grid(pairs, folds)
    (xmax, ymax) = find_max(pairs)
    
    grid = zeros(Int64, ymax, xmax)
    
    for pair in pairs
        grid[pair[2], pair[1]] = 1
    end
    
    return grid
end

make_grid (generic function with 1 method)

In [4]:
function fold_grid(grid, fold)
    fold_idx = fold[2]
    folded_grid = copy(grid)
    if fold[1] == "x"
        folded_grid = folded_grid[1:end, 1:fold_idx-1]
        
        for i in 1 : size(grid,2) - fold_idx
            folded_grid[1:end, fold_idx - i] = folded_grid[1:end, fold_idx - i] + grid[1:end, fold_idx + i]
        end
    elseif fold[1] == "y"
        folded_grid = folded_grid[1:fold[2]-1, 1:end]
        
        for j in 1 : size(grid,1) - fold_idx
            folded_grid[fold_idx - j, 1:end] = folded_grid[fold_idx - j, 1:end] + grid[fold_idx + j,1:end]
        end
    end     
    return folded_grid
end

fold_grid (generic function with 1 method)

In [9]:
grid = make_grid(pairs, folds)
grids = push!(Array{typeof(grid)}(undef, 0), grid)
counts = Array{Int64}(undef, 0)

for fold in folds
    push!(grids, fold_grid(grids[end], fold))
    
    count = 0
    for elem in grids[end]
        if elem > 0
            count += 1
        end
    end
    push!(counts, count)
end    

In [26]:
count = 0
for elem in grids[2]
    if elem > 0
        count += 1
    end
end    

grids[end]

6×40 Matrix{Int64}:
  4   2  11  2  0   0  13  4   0  0  14  …   0   6  1  0  0  38  9  20   0  0
 14   0   0  0  0  29   0  0  19  0  16      2   0  0  2  0   1  0   0  12  0
  2  12   3  0  0  22   0  0  14  0   4      6   0  0  0  0   8  0   0   6  0
 12   0   0  0  0   7  12  8  13  0   2     10   0  0  0  0   6  2   1   0  0
 10   0   0  0  0  15   0  0   3  0  30     15   0  0  5  0  25  0   0   0  0
 22   3   8  2  0   9   0  0   8  0   2  …   0  11  8  0  0  23  0   0   0  0

In [16]:
grids[end][1:end, 1:5]

6×5 Matrix{Int64}:
  4   2  11  2  0
 14   0   0  0  0
  2  12   3  0  0
 12   0   0  0  0
 10   0   0  0  0
 22   3   8  2  0

In [18]:
grids[end][1:end, 5:10]

6×6 Matrix{Int64}:
 0   0  13  4   0  0
 0  29   0  0  19  0
 0  22   0  0  14  0
 0   7  12  8  13  0
 0  15   0  0   3  0
 0   9   0  0   8  0

In [19]:
grids[end][1:end, 10:15]

6×6 Matrix{Int64}:
 0  14   0   0   2  0
 0  16   0   0  11  0
 0   4  32  15   4  0
 0   2   0   0   7  0
 0  30   0   0   7  0
 0   2   0   0   6  0

In [20]:
grids[end][1:end, 15:20]

6×6 Matrix{Int64}:
 0  13  0  0  5  0
 0  14  0  3  0  0
 0  14  6  0  0  0
 0  15  0  1  0  0
 0   7  0  8  0  0
 0   4  0  0  4  0

In [22]:
grids[end][1:end, 20:25]

6×6 Matrix{Int64}:
 0   8   6  4   0  0
 0   8   0  0   4  0
 0   5   0  0   4  0
 0   4  10  5   0  0
 0  10   0  2   0  0
 0   5   0  0  23  0

In [24]:
grids[end][1:end, 25:30]

6×6 Matrix{Int64}:
 0  24  16   1  7  0
 0   3   0   0  0  0
 0  26  17  11  0  0
 0   7   0   0  0  0
 0   2   0   0  0  0
 0   4  11   7  2  0

In [27]:
grids[end][1:end, 30:35]

6×6 Matrix{Int64}:
 0   0   6  1  0  0
 0   2   0  0  2  0
 0   6   0  0  0  0
 0  10   0  0  0  0
 0  15   0  0  5  0
 0   0  11  8  0  0

In [28]:
grids[end][1:end, 35:40]

6×6 Matrix{Int64}:
 0  38  9  20   0  0
 0   1  0   0  12  0
 0   8  0   0   6  0
 0   6  2   1   0  0
 0  25  0   0   0  0
 0  23  0   0   0  0